version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      dev-deps:
        patterns:
          - "pytest*"
          - "mypy*"
          - "coverage*"
          - "ruff"
      runtime-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "mypy*"
          - "coverage*"
          - "ruff"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
